INSERT INTO `property_list` (
    `property_id`, 
    `pr_status`, 
    `pr_display_status`, 
    `pr_list_type_id`, 
    `pr_type_id`, 
    `pr_sub_type_id`, 
    `mls_num`, 
    `size_sq_ft`, 
    `size_sq_mt`, 
    `size_lot`, 
    `size_units`, 
    `address`, 
    `unit_num`, 
    `city`, 
    `state`, 
    `county`, 
    `zip`, 
    `area`, 
    `bedrooms`, 
    `bathrooms`, 
    `half_baths`, 
    `third_baths`, 
    `fourth_baths`, 
    `year_built`, 
    `zoning_id`, 
    `virtual_tour`, 
    `map_embed`, 
    `property_title`, 
    `property_desc`, 
    `longitude`, 
    `latitude`, 
    `is_visible`, 
    `is_foreclosure`, 
    `is_featured`, 
    `is_construction`, 
    `month_built`, 
    `size_lot_mt`, 
    `room_type`, 
    `release_notes`
) VALUES (
    1000,
    'active',
    '',
    18,
    20,
    61,
    'TEST001',
    1800.00,
    167.22,
    5000.00,
    0,
    '123 Test Avenue',
    '',
    '1810',
    '23',
    '25',
    '77710',
    '5',
    3,
    2,
    1,
    0,
    0,
    2020,
    18,
    '',
    NULL,
    'Beautiful Test Property in Playa del Carmen',
    'This stunning 3-bedroom, 2.5-bathroom property features modern amenities and is located in the heart of Playa del Carmen. The property includes a spacious living area, updated kitchen, private garden, and is walking distance to the beach and 5th Avenue. Perfect for vacation rental or permanent residence. Property includes:\n\n- Modern kitchen with stainless steel appliances\n- Spacious bedrooms with built-in closets\n- Private garden and terrace\n- Secure parking\n- 24/7 security\n- Walking distance to beach and downtown\n- Excellent rental potential',
    '-87.0792092',
    '20.6390683',
    1,
    0,
    1,
    0,
    6,
    464.52,
    'bed',
    'Test property for demonstration purposes'
);

INSERT INTO `property_pricing` (
    `price_id`,
    `price_name`,
    `price_desc`,
    `price_amt`,
    `price_type`,
    `property_id`,
    `price_currency`
) VALUES (
    2000,
    'Excellent Value!',
    'Prime location property at competitive price',
    450000.00,
    '1',
    1000,
    'usd'
);