<?php
class Login {

	public $Username;
	public $Email;
	public $Userid;
	private $Password;
	public $Redirect = '/adm/listings';
	public $Return = '/adm/index';
	public $Message;
	public $Login = 0;

	public function __construct(){

	}

	public function isLogged(){
		if(isset($_SESSION['user']) && $_SESSION['user'] != ''){
			$this->Userid = $_SESSION['user'];
			//get user information
			$getUser = new SqlIt("SELECT username, email FROM users WHERE uid = ?","select",array($this->Userid));
			if($getUser->NumResults != 0){
				$this->Username = $getUser->Response[0]->username;
				$this->Email = $getUser->Response[0]->email;
				$this->Login = 1;
				//update timestamp
			}else{
				$this->Login = 0;
				$this->Message = '<div class="alert alert-danger text-center">You are not logged in. You are being redirected to the login page</div>';
			}

		}else{
			$this->Login = 0;
		}

	}

	public function logIn($user,$pass){
		$getUser = new SqlIt("SELECT uid FROM users WHERE username = ? AND password = MD5('".$pass."')","select",array($user));
		if($getUser->NumResults == 1){
			$this->Login = 1;
			$this->Message = '<div class="alert alert-success text-center">Login successfull, redirecting...</div>';
			$_SESSION['user'] = $getUser->Response[0]->uid;
		}else{
			$this->Login = 0;
			$this->Message = '<div class="alert alert-danger">The username or password was incorrect.</div>';
		}
	}

	public function forgotPass($email){
		//check username and email
		$resetPass = new SqlIt("SELECT uid, email FROM users WHERE email = ? OR username = ?","select",array($email));
		if($resetPass->NumResults == 1){
			$resetId = $resetPass->Response[0]->uid;
			$resetId = $resetId * 23;
			$resetId = $resetId + 5596;
			//send email
			$from = 'admin@miarealty.com.mx';// sender
		    $subject = 'Password Reset - MIA Realty Admin';
		    $message = 'You have requested to reset your password on the MIA Realty Control Panel. If you did not make this request, please ignore this email. Otherwise copy the link below into your browser to reset your password:
		    -------------------------------------------------------------------------------
		    https://miarealty.com.mx/adm/index.php?reset='.$resetId.'

		    1. Reset your password.
		    2. Login as normal.

		    *If you have any issues please contact tech support: info@grfreedom.com
		    -------------------------------------------------------------------------------
		    Please do not respond to this email, it was generated by the website.';
		    // message lines should not exceed 70 characters (PHP rule), so wrap it
		    $message = wordwrap($message, 70);
		    // send mail
		    mail($resetPass->Response[0]->email,$subject,$message,"From: $from\n");
		    $this->Message = '<div class="alert alert-success text-center">We have sent you an email with instructions to reset your password. Please remember to check your spam.</div>';
		}else{
			$this->Message = '<div class="alert alert-danger text-center">We could not find this username or email registered. Please make sure it is correct.</div>';
		}
	}

	public function resetPass($userid,$pass){
		if($userid != '' && $pass != ''){
			if(strlen($pass) > 5){
				$this->Message = '<div class="alert alert-danger">Your password must be at least 6 characters.</div>';
			}else{
				//recreate user id
				$userid = $userid - 5596;
				$userId = $userid / 23;

				$resetPass = new SqlIt("SELECT uid FROM users WHERE uid = ?","select",array($userid));
				if($resetPass->NumResults == 1){
					new SqlIt("UPDATE users SET password = MD5('".$pass."') WHERE uid = ?","update",array($userid));
					$this->Message = '<div class="alert alert-success text-center">Your password was reset correctly. Please click below to return to the login page now.<br><a href="index" class="btn btn-danger">LOGIN NOW</a></div>';
				}else{
					$this->Message = '<div class="alert alert-danger text-center">We apologize but this link is broken. Please make sure it was pasted correctly from the confirmation email.</div>';
				}
			}
		}
	}


}
